/**
 * Structured error codes and shape for agent consumption.
 * Aligned with 0.1.0 Error Taxonomy in docs/node-api-design.md
 */
export const ERROR_CODES = {
  DEVICE_USER_NOT_UNLOCKED: "DEVICE_USER_NOT_UNLOCKED",
  NOTIFICATION_ACCESS_DENIED: "NOTIFICATION_ACCESS_DENIED",
  NOTIFICATION_LISTENER_DISCONNECTED: "NOTIFICATION_LISTENER_DISCONNECTED",
  NOTIFICATION_QUERY_FAILED: "NOTIFICATION_QUERY_FAILED",
  NOTIFICATION_SERVICE_UNAVAILABLE: "NOTIFICATION_SERVICE_UNAVAILABLE",
  MEDIA_SESSION_EXPIRED: "MEDIA_SESSION_EXPIRED",
  MEDIA_SESSION_AMBIGUOUS: "MEDIA_SESSION_AMBIGUOUS",
  MEDIA_ACTION_UNSUPPORTED: "MEDIA_ACTION_UNSUPPORTED",
  MEDIA_POSTCONDITION_TIMEOUT: "MEDIA_POSTCONDITION_TIMEOUT",
  /** An action could not capture an application hierarchy. See failed-step diagnostics. */
  UI_TREE_UNAVAILABLE: "UI_TREE_UNAVAILABLE",
  SNAPSHOT_HIERARCHY_UNAVAILABLE: "SNAPSHOT_HIERARCHY_UNAVAILABLE",
  WAIT_TIMEOUT: "WAIT_TIMEOUT",
  ACTION_FAILED: "ACTION_FAILED",
  COMMAND_TIMEOUT: "COMMAND_TIMEOUT",
  COMMAND_CANCELLED: "COMMAND_CANCELLED",
  CONTAINER_LOST: "CONTAINER_LOST",
  /** Evidence could not be fully captured or persisted; inspect the retained manifest when available. */
  EVIDENCE_CAPTURE_FAILED: "EVIDENCE_CAPTURE_FAILED",
  /** Choose a new evidence output directory; existing destinations are never overwritten. */
  EVIDENCE_OUTPUT_EXISTS: "EVIDENCE_OUTPUT_EXISTS",
  /** The requested video session is unknown or invalid. */
  EVIDENCE_SESSION_NOT_FOUND: "EVIDENCE_SESSION_NOT_FOUND",
  /** Another video session owns the selected device lock. */
  EVIDENCE_RECORDING_ACTIVE: "EVIDENCE_RECORDING_ACTIVE",
  /** Verify recorder ownership and retained files before manual lock recovery. */
  EVIDENCE_RECOVERY_REQUIRED: "EVIDENCE_RECOVERY_REQUIRED",
  // Host
  HOST_DEPENDENCY_MISSING: "HOST_DEPENDENCY_MISSING",

  // Setup & Connectivity
  ADB_NOT_FOUND: "ADB_NOT_FOUND",
  NO_DEVICES: "NO_DEVICES",
  /** Recovery: pass `--device` (alias `--device-id`) when adb shows multiple targets. */
  MULTIPLE_DEVICES_DEVICE_ID_REQUIRED: "MULTIPLE_DEVICES_DEVICE_ID_REQUIRED",
  OPERATOR_NOT_INSTALLED: "OPERATOR_NOT_INSTALLED",
  /** Recovery: the `--device` serial is not connected (alias `--device-id`). */
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND", // Specific device ID provided but not connected

  // Execution & State
  EXECUTION_VALIDATION_FAILED: "EXECUTION_VALIDATION_FAILED",
  EXECUTION_ACTION_UNSUPPORTED: "EXECUTION_ACTION_UNSUPPORTED",
  EXECUTION_CONFLICT_IN_FLIGHT: "EXECUTION_CONFLICT_IN_FLIGHT",
  RESULT_ENVELOPE_TIMEOUT: "RESULT_ENVELOPE_TIMEOUT",
  RESULT_TRANSPORT_SPAWN_FAILED: "RESULT_TRANSPORT_SPAWN_FAILED",
  RESULT_TRANSPORT_EXITED: "RESULT_TRANSPORT_EXITED",
  RESULT_TRANSPORT_CANCELLED: "RESULT_TRANSPORT_CANCELLED",
  RESULT_TRANSPORT_FAILED: "RESULT_TRANSPORT_FAILED",
  RESULT_ENVELOPE_MALFORMED: "RESULT_ENVELOPE_MALFORMED",
  /** Raw XML could not be written to a new host artifact. The execution envelope is retained. */
  SNAPSHOT_ARTIFACT_WRITE_FAILED: "SNAPSHOT_ARTIFACT_WRITE_FAILED",
  SNAPSHOT_EXTRACTION_FAILED: "SNAPSHOT_EXTRACTION_FAILED",

  // CLI Usage
  MISSING_ARGUMENT: "MISSING_ARGUMENT",

  // UI & Nodes
  NODE_AMBIGUOUS: "NODE_AMBIGUOUS",
  CONTAINER_AMBIGUOUS: "CONTAINER_AMBIGUOUS",
  NODE_NOT_FOUND: "NODE_NOT_FOUND",
  NODE_NOT_CLICKABLE: "NODE_NOT_CLICKABLE",
  SECURITY_BLOCK_DETECTED: "SECURITY_BLOCK_DETECTED",
  CONTAINER_NOT_FOUND: "CONTAINER_NOT_FOUND",
  CONTAINER_NOT_SCROLLABLE: "CONTAINER_NOT_SCROLLABLE",
  GESTURE_FAILED: "GESTURE_FAILED",

  // On-screen log panel
  ON_SCREEN_LOG_SERVICE_UNAVAILABLE: "ON_SCREEN_LOG_SERVICE_UNAVAILABLE",
  ON_SCREEN_LOG_LAYOUT_INVALID: "ON_SCREEN_LOG_LAYOUT_INVALID",
  ON_SCREEN_LOG_RENDER_FAILED: "ON_SCREEN_LOG_RENDER_FAILED",
  ON_SCREEN_LOG_RENDER_TIMEOUT: "ON_SCREEN_LOG_RENDER_TIMEOUT",

  // Doctor & Host
  /** Daily log destination cannot be opened. Recovery: set CLAWPERATOR_LOG_DIR to a writable directory; advisory only. */
  LOG_DIRECTORY_UNWRITABLE: "LOG_DIRECTORY_UNWRITABLE",
  NODE_TOO_OLD: "NODE_TOO_OLD",
  ADB_SERVER_FAILED: "ADB_SERVER_FAILED",
  ADB_NO_USB_PERMISSIONS: "ADB_NO_USB_PERMISSIONS",
  DEVICE_UNAUTHORIZED: "DEVICE_UNAUTHORIZED",
  DEVICE_OFFLINE: "DEVICE_OFFLINE",
  DEVICE_SHELL_UNAVAILABLE: "DEVICE_SHELL_UNAVAILABLE",
  /** Installed release/debug Operator APK variant does not match `--operator-package`. */
  OPERATOR_VARIANT_MISMATCH: "OPERATOR_VARIANT_MISMATCH",
  DEVICE_DEV_OPTIONS_DISABLED: "DEVICE_DEV_OPTIONS_DISABLED",
  DEVICE_USB_DEBUGGING_DISABLED: "DEVICE_USB_DEBUGGING_DISABLED",
  DEVICE_ACCESSIBILITY_NOT_RUNNING: "DEVICE_ACCESSIBILITY_NOT_RUNNING",
  DEVICE_NOT_INTERACTIVE: "DEVICE_NOT_INTERACTIVE",
  ANDROID_BUILD_FAILED: "ANDROID_BUILD_FAILED",
  ANDROID_INSTALL_FAILED: "ANDROID_INSTALL_FAILED",
  ANDROID_APP_LAUNCH_FAILED: "ANDROID_APP_LAUNCH_FAILED",
  SMOKE_OPEN_SETTINGS_FAILED: "SMOKE_OPEN_SETTINGS_FAILED",
  SCRCPY_NOT_FOUND: "SCRCPY_NOT_FOUND",
  APK_VERSION_UNREADABLE: "APK_VERSION_UNREADABLE",
  APK_VERSION_INVALID: "APK_VERSION_INVALID",
  CLI_VERSION_INVALID: "CLI_VERSION_INVALID",
  VERSION_INCOMPATIBLE: "VERSION_INCOMPATIBLE",
  LOGCAT_UNAVAILABLE: "LOGCAT_UNAVAILABLE",
  ANDROID_SDK_TOOL_MISSING: "ANDROID_SDK_TOOL_MISSING",
  EMULATOR_NOT_FOUND: "EMULATOR_NOT_FOUND",
  EMULATOR_ALREADY_RUNNING: "EMULATOR_ALREADY_RUNNING",
  EMULATOR_NOT_RUNNING: "EMULATOR_NOT_RUNNING",
  EMULATOR_UNSUPPORTED: "EMULATOR_UNSUPPORTED",
  EMULATOR_CREATE_FAILED: "EMULATOR_CREATE_FAILED",
  EMULATOR_START_FAILED: "EMULATOR_START_FAILED",
  EMULATOR_STOP_FAILED: "EMULATOR_STOP_FAILED",
  EMULATOR_DELETE_FAILED: "EMULATOR_DELETE_FAILED",
  EMULATOR_BOOT_TIMEOUT: "EMULATOR_BOOT_TIMEOUT",
  ANDROID_SYSTEM_IMAGE_INSTALL_FAILED: "ANDROID_SYSTEM_IMAGE_INSTALL_FAILED",
  ANDROID_AVD_CREATE_FAILED: "ANDROID_AVD_CREATE_FAILED",
  AGENT_SKILLS_STALE: "AGENT_SKILLS_STALE",

  // Daemon lifecycle
  DAEMON_START_FAILED: "DAEMON_START_FAILED",
  DAEMON_STOP_FAILED: "DAEMON_STOP_FAILED",
  DAEMON_PROXY_ERROR: "DAEMON_PROXY_ERROR",

  // Operator install
  OPERATOR_DOWNLOAD_UNSUPPORTED: "OPERATOR_DOWNLOAD_UNSUPPORTED",
  OPERATOR_METADATA_INVALID: "OPERATOR_METADATA_INVALID",
  OPERATOR_DOWNLOAD_FAILED: "OPERATOR_DOWNLOAD_FAILED",
  OPERATOR_CHECKSUM_FAILED: "OPERATOR_CHECKSUM_FAILED",
  OPERATOR_APK_NOT_FOUND: "OPERATOR_APK_NOT_FOUND",
  OPERATOR_INSTALL_FAILED: "OPERATOR_INSTALL_FAILED",
  OPERATOR_GRANT_FAILED: "OPERATOR_GRANT_FAILED",
  OPERATOR_VERIFY_FAILED: "OPERATOR_VERIFY_FAILED",

  // Recording
  RECORDING_ALREADY_IN_PROGRESS: "RECORDING_ALREADY_IN_PROGRESS",
  RECORDING_NOT_IN_PROGRESS: "RECORDING_NOT_IN_PROGRESS",
  RECORDING_SESSION_NOT_FOUND: "RECORDING_SESSION_NOT_FOUND",
  RECORDING_PULL_FAILED: "RECORDING_PULL_FAILED",
  RECORDING_PARSE_FAILED: "RECORDING_PARSE_FAILED",
  RECORDING_EXPORT_FAILED: "RECORDING_EXPORT_FAILED",
  RECORDING_COMPARE_FAILED: "RECORDING_COMPARE_FAILED",
  RECORDING_SCHEMA_VERSION_UNSUPPORTED: "RECORDING_SCHEMA_VERSION_UNSUPPORTED",

  // Internal / Other
  /** ADB broadcast dispatch to the Operator package failed. */
  BROADCAST_FAILED: "BROADCAST_FAILED",
  /** Request size limit or Android query_ui response exceeding 256 KiB. */
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  DOCTOR_FAILED: "DOCTOR_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ClawperatorError {
  code: ErrorCode;
  message: string;
  hint?: string;
  details?: Record<string, unknown>;
  fallback_instructions_path?: string;
}

export interface TimeoutDiagnostics {
  code: typeof ERROR_CODES.RESULT_ENVELOPE_TIMEOUT;
  message: string;
  details?: Record<string, unknown>;
  lastCorrelatedEvents?: string[];
  broadcastDispatchStatus?: string;
  deviceId?: string;
  operatorPackage?: string;
}

export interface BroadcastDiagnostics {
  code: typeof ERROR_CODES.BROADCAST_FAILED | typeof ERROR_CODES.OPERATOR_NOT_INSTALLED;
  message: string;
  details?: Record<string, unknown>;
  lastCorrelatedEvents?: string[];
  broadcastDispatchStatus?: string;
  deviceId?: string;
  operatorPackage?: string;
}

export function isClawperatorError(e: unknown): e is ClawperatorError {
  return (
    typeof e === "object" &&
    e !== null &&
    "code" in e &&
    typeof (e as ClawperatorError).code === "string" &&
    "message" in e &&
    typeof (e as ClawperatorError).message === "string"
  );
}
