/**
 * Hard validation limits (v1) - must match design doc and Android runtime.
 */
export const LIMITS = {
  MAX_EXECUTION_ACTIONS: 50,
  MAX_EXECUTION_TIMEOUT_MS: 120_000,
  MIN_EXECUTION_TIMEOUT_MS: 1_000,
  MAX_PAYLOAD_BYTES: 64_000,
  MAX_RETRY_ATTEMPTS_PER_STEP: 10,
  MAX_SNAPSHOT_LINES: 2_000,
  MAX_SNAPSHOT_BYTES: 262_144,
  MAX_BEST_EFFORT_STEPS: 30,
  MAX_BEST_EFFORT_RUNTIME_MS: 180_000,
  MAX_CONSECUTIVE_FAILED_ATTEMPTS: 5,
  MAX_ID_LENGTH: 128,
  MAX_SOURCE_LENGTH: 64,
  MAX_MATCHER_VALUE_LENGTH: 512,
} as const;

export type Limits = typeof LIMITS;
